/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.masgeek.api

import org.junit.jupiter.api.BeforeEach

class PushBulletTest {

    private lateinit var apiClient: ApiClient

    @BeforeEach
    fun setUp() {
        val baseUrl = "https://api.example.com/"
        val customHeaders = mapOf("Authorization" to "Bearer YourAccessToken")

        apiClient = ApiClient(baseUrl, customHeaders)
    }
}
