/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.masgeek.api

import com.masgeek.api.dto.PushMessage
import com.masgeek.api.dto.PushBulletUser
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

class PushBullet(private val baseUrl: String, private val headers: Map<String, String> = emptyMap()) {

    val apiClient = ApiClient(baseUrl = baseUrl, headers = headers)
    fun getUser(pushMessage: PushMessage): Boolean {

        val call = apiClient.pushBulletService.getCurrentUser()
        call.enqueue(object : Callback<PushBulletUser> {
            override fun onResponse(call: Call<PushBulletUser>, response: Response<PushBulletUser>) {
                if (response.isSuccessful) {
                    val user = response.body()

                    println("User ID: ${user!!.userIdentity}, Name: ${user.name}, Email: ${user.email}")
                } else {
                    println("Error: ${response.code()} - ${response.message()}")
                }
            }

            override fun onFailure(call: Call<PushBulletUser>, t: Throwable) {
                println("Error: ${t.message}")
            }

        })
        return false
    }
}
