name: Create PR
on:
  push:
    branches:
      - develop
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Create Release PR
        uses: desbravacloud/action-create-pull-requests@v1
        with:
#          origin-branch: 'develop'
          target-branch: 'main'
          custom-title: 'PR created'
          custom-body: 'Please, check thease changes'
