name: Create PR
on:
  push:
    branches:
      - develop
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Create Release PR
        uses: desbravacloud/action-create-pull-requests@v1
        with:
#          origin-branch: 'develop'
          target-branch: 'main'
          custom-title: 'PR created'
          custom-body: 'Please, check thease changes'
